# Generated by Django 3.2.2 on 2021-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggapp', '0002_auto_20210528_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M'),
        ),
    ]
